#!/usr/bin/env python3
"""
checkstyle_setup.py - Set up Checkstyle with an Effective Java-aligned configuration.

Usage:
    python checkstyle_setup.py [--output-dir ./]

Generates:
    effective-java-checkstyle.xml  - Checkstyle rules mapped to Effective Java items
    run_checkstyle.sh              - Shell script to run Checkstyle on src/

Each config section references the Effective Java item it enforces.
"""

import argparse
import os
import pathlib
import stat
import sys
import urllib.request
import urllib.error

CHECKSTYLE_VERSION = "10.14.2"
CHECKSTYLE_JAR = f"checkstyle-{CHECKSTYLE_VERSION}-all.jar"
CHECKSTYLE_URL = (
    f"https://github.com/checkstyle/checkstyle/releases/download/"
    f"checkstyle-{CHECKSTYLE_VERSION}/{CHECKSTYLE_JAR}"
)

CHECKSTYLE_XML = """\
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
    "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN"
    "https://checkstyle.org/dtds/configuration_1_3.dtd">

<!--
  Effective Java - Checkstyle Configuration
  Each module references the Effective Java item it enforces.
  Book: "Effective Java" by Joshua Bloch, 3rd Edition.
-->
<module name="Checker">
  <property name="severity" value="warning"/>

  <module name="TreeWalker">

    <!--
      Item 15: Minimize the accessibility of classes and members.
      Prefer private fields; expose only what is necessary.
    -->
    <module name="VisibilityModifier">
      <property name="protectedAllowed" value="false"/>
      <property name="publicMemberPattern" value="^serialVersionUID$"/>
    </module>

    <!--
      Item 17: Minimize mutability — utility/helper classes should be final.
      FinalClass flags classes with only private constructors that are not final.
    -->
    <module name="FinalClass"/>

    <!--
      Item 10: Obey the general contract when overriding equals.
      Always override hashCode when you override equals.
    -->
    <module name="EqualsHashCode"/>

    <!--
      Item 34: Use enums instead of int constants.
      Magic numbers in code signal that an enum or named constant should be used.
    -->
    <module name="MagicNumber">
      <property name="ignoreNumbers" value="-1, 0, 1, 2"/>
      <property name="ignoreAnnotation" value="true"/>
      <property name="ignoreHashCodeMethod" value="true"/>
    </module>

    <!--
      Item 77: Don't ignore exceptions.
      Empty catch blocks hide failures; always handle or rethrow.
    -->
    <module name="EmptyCatchBlock">
      <property name="exceptionVariableName" value="expected|ignore"/>
    </module>

    <!--
      Item 2: Consider a builder when faced with many constructor parameters.
      More than 3 parameters is a signal to introduce a Builder.
    -->
    <module name="ParameterNumber">
      <property name="max" value="3"/>
      <property name="tokens" value="METHOD_DEF, CTOR_DEF"/>
    </module>

    <!--
      General best practice aligned with Effective Java's emphasis on small,
      focused methods. Methods longer than 30 lines are harder to reason about.
    -->
    <module name="MethodLength">
      <property name="max" value="30"/>
      <property name="countEmpty" value="false"/>
    </module>

    <!--
      Item 11: Always override toString.
      Not directly checkable, but HideUtilityClassConstructor complements
      Item 4 (enforce non-instantiability with private constructor).
    -->
    <module name="HideUtilityClassConstructor"/>

    <!--
      Item 57: Minimize the scope of local variables.
      Inner assignments make scope harder to reason about.
    -->
    <module name="InnerAssignment"/>

    <!--
      Item 67: Optimize judiciously — avoid redundant string concatenation in loops.
    -->
    <module name="StringLiteralEquality"/>

  </module>
</module>
"""

RUN_SCRIPT = """\
#!/usr/bin/env bash
# run_checkstyle.sh
# Runs Checkstyle with the Effective Java configuration against src/
# Generated by checkstyle_setup.py

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
JAR="${SCRIPT_DIR}/{jar}"
CONFIG="${SCRIPT_DIR}/effective-java-checkstyle.xml"
SRC_DIR="${1:-src}"

if [[ ! -f "$JAR" ]]; then
  echo "ERROR: Checkstyle jar not found at $JAR"
  echo "Run: python checkstyle_setup.py --output-dir \\"$(dirname "$JAR")\\""
  exit 1
fi

if [[ ! -d "$SRC_DIR" ]]; then
  echo "ERROR: Source directory not found: $SRC_DIR"
  echo "Usage: ./run_checkstyle.sh [src-dir]"
  exit 1
fi

echo "Running Checkstyle on $SRC_DIR ..."
java -jar "$JAR" -c "$CONFIG" -r "$SRC_DIR"
echo "Done."
""".format(jar=CHECKSTYLE_JAR)


def download_jar(output_dir: pathlib.Path) -> bool:
    jar_path = output_dir / CHECKSTYLE_JAR
    if jar_path.exists():
        print(f"Checkstyle jar already present: {jar_path}")
        return True
    print(f"Downloading Checkstyle {CHECKSTYLE_VERSION} from GitHub ...")
    try:
        urllib.request.urlretrieve(CHECKSTYLE_URL, jar_path)
        print(f"Downloaded: {jar_path}")
        return True
    except urllib.error.URLError as exc:
        print(f"Download failed: {exc}")
        print()
        print("To install manually:")
        print(f"  curl -L -o {jar_path} \\")
        print(f"    {CHECKSTYLE_URL}")
        return False


def write_file(path: pathlib.Path, content: str, executable: bool = False) -> None:
    path.write_text(content, encoding="utf-8")
    if executable:
        path.chmod(path.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    print(f"Wrote: {path}")


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Set up Checkstyle with an Effective Java-aligned configuration."
    )
    parser.add_argument(
        "--output-dir",
        default=".",
        help="Directory to write config files and download the jar (default: ./)",
    )
    args = parser.parse_args()

    output_dir = pathlib.Path(args.output_dir).resolve()
    output_dir.mkdir(parents=True, exist_ok=True)

    download_jar(output_dir)

    write_file(output_dir / "effective-java-checkstyle.xml", CHECKSTYLE_XML)
    write_file(output_dir / "run_checkstyle.sh", RUN_SCRIPT, executable=True)

    print()
    print("Setup complete.")
    print(f"  Config : {output_dir / 'effective-java-checkstyle.xml'}")
    print(f"  Runner : {output_dir / 'run_checkstyle.sh'}")
    print()
    print("Run Checkstyle:")
    print(f"  cd {output_dir} && ./run_checkstyle.sh [src-dir]")


if __name__ == "__main__":
    main()
